/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as HubBuilderRouteImport } from './routes/hub-builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmVolumeRouteImport } from './routes/crm.volume'
import { Route as CrmTemplatesRouteImport } from './routes/crm.templates'
import { Route as CrmDashboardRouteImport } from './routes/crm.dashboard'
import { Route as CrmContingenciaRouteImport } from './routes/crm.contingencia'
import { Route as CrmCanaisRouteImport } from './routes/crm.canais'
import { Route as CrmAlertasRouteImport } from './routes/crm.alertas'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as CrmClinicasIndexRouteImport } from './routes/crm.clinicas.index'
import { Route as CrmClinicasIdRouteImport } from './routes/crm.clinicas.$id'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as ComercialNovaVendaRouteImport } from './routes/comercial.nova-venda'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingIdRouteImport } from './routes/onboarding.$id'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const HubBuilderRoute = HubBuilderRouteImport.update({
  id: '/hub-builder',
  path: '/hub-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmVolumeRoute = CrmVolumeRouteImport.update({
  id: '/crm/volume',
  path: '/crm/volume',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmTemplatesRoute = CrmTemplatesRouteImport.update({
  id: '/crm/templates',
  path: '/crm/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmDashboardRoute = CrmDashboardRouteImport.update({
  id: '/crm/dashboard',
  path: '/crm/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContingenciaRoute = CrmContingenciaRouteImport.update({
  id: '/crm/contingencia',
  path: '/crm/contingencia',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCanaisRoute = CrmCanaisRouteImport.update({
  id: '/crm/canais',
  path: '/crm/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmAlertasRoute = CrmAlertasRouteImport.update({
  id: '/crm/alertas',
  path: '/crm/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmClinicasIndexRoute = CrmClinicasIndexRouteImport.update({
  id: '/crm/clinicas/',
  path: '/crm/clinicas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmClinicasIdRoute = CrmClinicasIdRouteImport.update({
  id: '/crm/clinicas/$id',
  path: '/crm/clinicas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialNovaVendaRoute = ComercialNovaVendaRouteImport.update({
  id: '/comercial/nova-venda',
  path: '/comercial/nova-venda',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIdRoute = OnboardingIdRouteImport.update({
  id: '/onboarding/$id',
  path: '/onboarding/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hub-builder': typeof HubBuilderRoute
  '/tv': typeof TvRoute
  '/auth/login': typeof AuthLoginRoute
  '/crm/alertas': typeof CrmAlertasRoute
  '/crm/canais': typeof CrmCanaisRoute
  '/crm/contingencia': typeof CrmContingenciaRoute
  '/crm/dashboard': typeof CrmDashboardRoute
  '/crm/templates': typeof CrmTemplatesRoute
  '/crm/volume': typeof CrmVolumeRoute
  '/crm/': typeof CrmIndexRoute
  '/crm/clinicas/$id': typeof CrmClinicasIdRoute
  '/crm/clinicas/': typeof CrmClinicasIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/comercial/nova-venda': typeof ComercialNovaVendaRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/onboarding/$id': typeof OnboardingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hub-builder': typeof HubBuilderRoute
  '/tv': typeof TvRoute
  '/auth/login': typeof AuthLoginRoute
  '/crm/alertas': typeof CrmAlertasRoute
  '/crm/canais': typeof CrmCanaisRoute
  '/crm/contingencia': typeof CrmContingenciaRoute
  '/crm/dashboard': typeof CrmDashboardRoute
  '/crm/templates': typeof CrmTemplatesRoute
  '/crm/volume': typeof CrmVolumeRoute
  '/crm': typeof CrmIndexRoute
  '/crm/clinicas/$id': typeof CrmClinicasIdRoute
  '/crm/clinicas': typeof CrmClinicasIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/comercial/nova-venda': typeof ComercialNovaVendaRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/onboarding/$id': typeof OnboardingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hub-builder': typeof HubBuilderRoute
  '/tv': typeof TvRoute
  '/auth/login': typeof AuthLoginRoute
  '/crm/alertas': typeof CrmAlertasRoute
  '/crm/canais': typeof CrmCanaisRoute
  '/crm/contingencia': typeof CrmContingenciaRoute
  '/crm/dashboard': typeof CrmDashboardRoute
  '/crm/templates': typeof CrmTemplatesRoute
  '/crm/volume': typeof CrmVolumeRoute
  '/crm/': typeof CrmIndexRoute
  '/crm/clinicas/$id': typeof CrmClinicasIdRoute
  '/crm/clinicas/': typeof CrmClinicasIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/comercial/nova-venda': typeof ComercialNovaVendaRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/onboarding/$id': typeof OnboardingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hub-builder'
    | '/tv'
    | '/auth/login'
    | '/crm/alertas'
    | '/crm/canais'
    | '/crm/contingencia'
    | '/crm/dashboard'
    | '/crm/templates'
    | '/crm/volume'
    | '/crm/'
    | '/crm/clinicas/$id'
    | '/crm/clinicas/'
    | '/clientes/'
    | '/clientes/$id'
    | '/comercial/nova-venda'
    | '/onboarding/'
    | '/onboarding/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hub-builder'
    | '/tv'
    | '/auth/login'
    | '/crm/alertas'
    | '/crm/canais'
    | '/crm/contingencia'
    | '/crm/dashboard'
    | '/crm/templates'
    | '/crm/volume'
    | '/crm'
    | '/crm/clinicas/$id'
    | '/crm/clinicas'
    | '/clientes'
    | '/clientes/$id'
    | '/comercial/nova-venda'
    | '/onboarding'
    | '/onboarding/$id'
  id:
    | '__root__'
    | '/'
    | '/hub-builder'
    | '/tv'
    | '/auth/login'
    | '/crm/alertas'
    | '/crm/canais'
    | '/crm/contingencia'
    | '/crm/dashboard'
    | '/crm/templates'
    | '/crm/volume'
    | '/crm/'
    | '/crm/clinicas/$id'
    | '/crm/clinicas/'
    | '/clientes/'
    | '/clientes/$id'
    | '/comercial/nova-venda'
    | '/onboarding/'
    | '/onboarding/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HubBuilderRoute: typeof HubBuilderRoute
  TvRoute: typeof TvRoute
  AuthLoginRoute: typeof AuthLoginRoute
  CrmAlertasRoute: typeof CrmAlertasRoute
  CrmCanaisRoute: typeof CrmCanaisRoute
  CrmContingenciaRoute: typeof CrmContingenciaRoute
  CrmDashboardRoute: typeof CrmDashboardRoute
  CrmTemplatesRoute: typeof CrmTemplatesRoute
  CrmVolumeRoute: typeof CrmVolumeRoute
  CrmIndexRoute: typeof CrmIndexRoute
  CrmClinicasIdRoute: typeof CrmClinicasIdRoute
  CrmClinicasIndexRoute: typeof CrmClinicasIndexRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ComercialNovaVendaRoute: typeof ComercialNovaVendaRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  OnboardingIdRoute: typeof OnboardingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub-builder': {
      id: '/hub-builder'
      path: '/hub-builder'
      fullPath: '/hub-builder'
      preLoaderRoute: typeof HubBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/volume': {
      id: '/crm/volume'
      path: '/crm/volume'
      fullPath: '/crm/volume'
      preLoaderRoute: typeof CrmVolumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/templates': {
      id: '/crm/templates'
      path: '/crm/templates'
      fullPath: '/crm/templates'
      preLoaderRoute: typeof CrmTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/dashboard': {
      id: '/crm/dashboard'
      path: '/crm/dashboard'
      fullPath: '/crm/dashboard'
      preLoaderRoute: typeof CrmDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/contingencia': {
      id: '/crm/contingencia'
      path: '/crm/contingencia'
      fullPath: '/crm/contingencia'
      preLoaderRoute: typeof CrmContingenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/canais': {
      id: '/crm/canais'
      path: '/crm/canais'
      fullPath: '/crm/canais'
      preLoaderRoute: typeof CrmCanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/alertas': {
      id: '/crm/alertas'
      path: '/crm/alertas'
      fullPath: '/crm/alertas'
      preLoaderRoute: typeof CrmAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/clinicas/': {
      id: '/crm/clinicas/'
      path: '/crm/clinicas'
      fullPath: '/crm/clinicas/'
      preLoaderRoute: typeof CrmClinicasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/clinicas/$id': {
      id: '/crm/clinicas/$id'
      path: '/crm/clinicas/$id'
      fullPath: '/crm/clinicas/$id'
      preLoaderRoute: typeof CrmClinicasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/nova-venda': {
      id: '/comercial/nova-venda'
      path: '/comercial/nova-venda'
      fullPath: '/comercial/nova-venda'
      preLoaderRoute: typeof ComercialNovaVendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$id': {
      id: '/onboarding/$id'
      path: '/onboarding/$id'
      fullPath: '/onboarding/$id'
      preLoaderRoute: typeof OnboardingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HubBuilderRoute: HubBuilderRoute,
  TvRoute: TvRoute,
  AuthLoginRoute: AuthLoginRoute,
  CrmAlertasRoute: CrmAlertasRoute,
  CrmCanaisRoute: CrmCanaisRoute,
  CrmContingenciaRoute: CrmContingenciaRoute,
  CrmDashboardRoute: CrmDashboardRoute,
  CrmTemplatesRoute: CrmTemplatesRoute,
  CrmVolumeRoute: CrmVolumeRoute,
  CrmIndexRoute: CrmIndexRoute,
  CrmClinicasIdRoute: CrmClinicasIdRoute,
  CrmClinicasIndexRoute: CrmClinicasIndexRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ClientesIdRoute: ClientesIdRoute,
  ComercialNovaVendaRoute: ComercialNovaVendaRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  OnboardingIdRoute: OnboardingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
